# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66b718e07249941f61c649b9c908683ec52282a32118c82a38169740c02d042d1953390bac63d8c5618b8cc69fd8df724babafa0607ad3754ef2133f22e7a49e

test:
  secret_key_base: 944289eb0d98388082bb6eff59ecdadd54b057afd959142cbf45b7c43c639eefdbf4e58d2cad10afc4b0fcca188276087150dc9cae396e001a90897dd6702691

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
